### ISSUE TITLE
BUG: client.get_model crashes if run on notebook 

### ISSUE THREAD

**Issue by MiNeves00** [TensorOpsAI/LLMstudio#23]
### System Info

client.get_model crashes if run on notebook immediately after setting up client. 
If we wait for 1-2 sec and then run it works perfectly. 

This behaviour is not seen when running the same code but on a script instead of a jupyter notebook.

### Related Components

- [X] API
- [ ] SDK
- [ ] UI

### Reproduction

Put this in a jupyter notebook cell and click run all. (Check if OpenAI key is previously setup)

```
from llmstudio.models import OpenAIClient
client = OpenAIClient()
model = client.get_model(model_name="gpt-3.5-turbo")
```

### Expected behavior

model would be created without error

**Comment by MiNeves00** [comment]
![Screenshot 2023-10-23 at 12 16 36](https://github.com/TensorOpsAI/LLMStudio/assets/61327611/ff594053-5a9a-4bd7-8eb6-419068b2c707)

**Comment by reiid00** [comment]
Fixed the issue where get_model was crashing in Jupyter notebooks.

The root cause was identified as a timing issue between API initialisation and subsequent API access. In a Jupyter notebook environment, running both the API initialisation and get_model in quick succession led to a crash, outputting an error indicating that the API was not running yet.

To address this, a retry mechanism in the _check_api_access method was added. This adds persistence to the API access validation process, preventing the notebook cell from crashing.
